#!/usr/bin/env bash
# Bash script that install and configurate a nginx web server
# to execute in remote server: ssh USER@IP "bash -s" -- < ./1-install_nginx_web_server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod ugo+w /var/www/html/index.nginx-debian.html
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sudo systemctl start nginx
