#!/usr/bin/env bash
# Bash script that install and configurate a nginx web server
# to execute in remote server: ssh USER@IP "bash -s" -- < ./3-redirection
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod ugo+w /var/www/html/index.nginx-debian.html
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
set_redirect_404="error_page 404 /404.html;\nlocation = /404.html { internal; }"
sudo sed -i "/listen 80 default_server/a $set_redirect_404" /etc/nginx/sites-available/default
sudo service nginx restart
