#!/usr/bin/env bash
# that displays Holberton School 10 times, but for the 9th iteration,
# displays Holberton School and then Hi on a new line.
x=0
while [ $x -le 10 ]
do
    if [ $x -eq 9 ]
    then
	echo "Hi"
    else
	echo "Holberton School"
    fi
    let x++
done
