#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times
x=0
while [ $x -le 9 ]
do
    if [ $x -eq 3 ]
    then
	echo "bad luck"
    elif [ $x -eq 7 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    let x++
done
