#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
hour=0
minutes=1
while [ $hour -le 12 ]
do
    echo "Hour: "$hour
    let minutes=1
    while [ $minutes -le 59 ]
    do
	echo $minutes
	let minutes++
    done
    let hour++
done
