#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times
hour=0
minutes=1
while [ $hour -le 12 ]
do
    echo "Hour: "$hour
    for minutes in {1..59}
    do
	echo $minutes
    done
    let hour++
done
