#!/usr/bin/env bash
# Script that change localhost IP for 127.0.0.2 and facebook IP for 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i 's/^127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
